# Gradle 设置
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.parallel=true

# Mod 基本信息
mod_id=cloudclient
mod_name=Cloud Client
mod_version=1.0.0

# Minecraft 与 Forge 版本（Forge 1.8.9）
minecraft_version=1.8.9
forge_version=11.15.1.2318

# 映射通道和版本（推荐使用稳定版）
mappings_channel=stable
mappings_version=20
